In [6]:
import pandas as pd
import numpy as np

In [7]:
bonds = pd.read_csv('bonds.csv')
events = pd.read_csv('events.csv')

In [8]:
bonds.head()

  BondID  Coupon  Frequency  MonthsSinceCoupon
0  BOND1    0.05          2                  3
1  BOND2    0.04          1                  6
2  BOND3    0.06          2                  4
3  BOND4    0.03          1                  6
4  BOND5    0.07          2                  1

In [9]:
events.head()

   EventID Desk  Trader BondID BuySell  Quantity  CleanPrice
0        1   NY  T_NY_2  BOND1    SELL        50       99.37
1        2   NY  T_NY_2  BOND5    SELL        60      106.56
2        3   NY  T_NY_1  BOND3    SELL        40      103.46
3        4   LN  T_LN_1  BOND5    SELL        20      105.77
4        5   HK  T_HK_2  BOND1     BUY        20       99.64

In [22]:
# It's good practice to initialize the column first
bonds['accrued_interest'] = 0.0 
bonds.drop(columns=['accured_interest'], inplace=True)
for index, row in bonds.iterrows():
    bond = row['BondID']
    coupon_rate = row['Coupon']
    frequency = row['Frequency']
    face_value = 100
    pay_interval = 12 / frequency
    accrued_fraction = row['MonthsSinceCoupon'] / pay_interval
    
    # Calculate the value
    calculated_interest = (coupon_rate / frequency) * accrued_fraction * face_value
    
    # FIX: Write directly to the main DataFrame using .loc
    bonds.loc[index, 'accrued_interest'] = calculated_interest

# Save new precomputed bonds 
bonds.to_csv('bonds_precomputed.csv', index=False)

Metrics: 
- Position: total buy - total sell
- Accured Intested : 
- Dirty Price
- Present value 
- Change in present value