In [1]:
import pandas as pd
import numpy as np

In [2]:
bonds = pd.read_csv('bonds.csv')
events = pd.read_csv('events.csv')

In [3]:
bonds.head()

  Unnamed: 0 Unnamed: 1 Unnamed: 2         Unnamed: 3
0     BondID     Coupon  Frequency  MonthsSinceCoupon
1      BOND1       0.05          2                  3
2      BOND2       0.04          1                  6
3      BOND3       0.06          2                  4
4      BOND4       0.03          1                  6

In [4]:
events.head()

   EventID Desk  Trader BondID BuySell  Quantity  CleanPrice
0        1   NY  T_NY_2  BOND1    SELL        50       99.37
1        2   NY  T_NY_2  BOND5    SELL        60      106.56
2        3   NY  T_NY_1  BOND3    SELL        40      103.46
3        4   LN  T_LN_1  BOND5    SELL        20      105.77
4        5   HK  T_HK_2  BOND1     BUY        20       99.64

Metrics: 
- Position
- Accured Intested 
- Dirty Price
- Present value 
- Change in present value